
 Movie.create(title: "Point Break", director: "Kathryn Bigelow", year: "1991", format: "VHS", inventory: 3)
 Movie.create(title: "Roadhouse", director: "Rowdy Herrington", year: "1989", format: "VHS", inventory: 3)
 Movie.create(title: "From Dusk Til Dawn", director: "Robert Rodriquez", year: "1996", format: "VHS", inventory: 3)
 Movie.create(title: "True Romance", director: "Tony Scott", year: "1993", format: "VHS", inventory: 3)
 Movie.create(title: "They Live", director: "John Carpenter", year: "1988", format: "VHS", inventory: 3)
 Movie.create(title: "Seven Samurai", director: "Akira Kurosawa", year: "1934", format: "VHS", inventory: 3)
 Movie.create(title: "Invasion of The Body Snatchers", director: "Philip Kaufman", year: "1978", format: "VHS", inventory: 3)
 Movie.create(title: "Night of The Living Dead", director: "George A. Romero", year: "1986", format: "VHS", inventory: 3)
 Movie.create(title: "The Maltese Falcon", director: "John Huston", year: "1941", format: "VHS", inventory: 3)
 Movie.create(title: "Face Off", director: "John Woo", year: "1997", format: "VHS", inventory: 3)

 Movie.create(title: "Point Break", director: "Kathryn Bigelow", year: "1991", format: "DVD", inventory: 3)
 Movie.create(title: "Roadhouse", director: "Rowdy Herrington", year: "1989", format: "DVD", inventory: 3)
 Movie.create(title: "From Dusk Til Dawn", director: "Robert Rodriquez", year: "1996", format: "DVD", inventory: 3)
 Movie.create(title: "True Romance", director: "Tony Scott", year: "1993", format: "DVD", inventory: 3)
 Movie.create(title: "They Live", director: "John Carpenter", year: "1988", format: "DVD", inventory: 3)
 Movie.create(title: "Seven Samurai", director: "Akira Kurosawa", year: "1934", format: "DVD", inventory: 3)
 Movie.create(title: "Invasion of The Body Snatchers", director: "Philip Kaufman", year: "1978", format: "DVD", inventory: 3)
 Movie.create(title: "Night of The Living Dead", director: "George A. Romero", year: "1986", format: "DVD", inventory: 3)
 Movie.create(title: "The Maltese Falcon", director: "John Huston", year: "1941", format: "DVD", inventory: 3)
 Movie.create(title: "Face Off", director: "John Woo", year: "1997", format: "DVD", inventory: 3)

User.create(name: "Jerry", username: "prognosis_negative", password: "krypton")
User.create(name: "George", username: "coco_the_monkey", password: "bosco")
User.create(name: "Elaine", username: "little_kicks", password: "dufus")
User.create(name: "Kramer", username: "Kramerica", password: "moviephone")

