Movie.create(title: "Point Break", director: "Kathryn Bigelow", year: "1991" )
Movie.create(title: "Roadhouse", director: "Rowdy Herrington", year: "1989")
Movie.create(title: "From Dusk Til Dawn", director: "Robert Rodriquez", year: "1996")
Movie.create(title: "True Romance", director: "Tony Scott", year: "1993")
Movie.create(title: "They Live", director: "John Carpenter", year: "1988")
Movie.create(title: "Seven Samurai", director: "Akira Kurosawa", year: "1954")
Movie.create(title: "Invasion of The Body Snatchers", director: "Philip Kaufman", year: "1978")
Movie.create(title: "Night of The Living Dead", director: "George A. Romero", year: "1986")
Movie.create(title: "The Maltese Falcon", director: "John Huston", year: "1941")
Movie.create(title: "Face Off", director: "John Woo", year: "1997")
